# Generated by Django 5.1.2 on 2025-08-20 18:55

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientID', models.CharField(blank=True, max_length=50, verbose_name='Patient ID')),
                ('patientName', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('patientPhoneNo', models.PositiveSmallIntegerField(blank=True, default='0', verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=48, verbose_name='Product Name')),
                ('medCategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharmacyapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='MedicineProcureDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNo', models.CharField(default='1', max_length=50, verbose_name='Batch Number')),
                ('pack', models.PositiveSmallIntegerField(default=1, verbose_name='No. of tablets per strip/bottle')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Number of strips/pieces purchased')),
                ('pricePerStrip', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Price per strip/piece')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='M.R.P. per Strip')),
                ('dateOfPurchase', models.DateField(default=django.utils.timezone.now, verbose_name='Date Of Purchase')),
                ('expiryDate', models.DateField(verbose_name='Expiry Date')),
                ('noOfTablets', models.PositiveSmallIntegerField(default=0)),
                ('pricePerTablet', models.DecimalField(decimal_places=2, default='0.01', max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicine')),
                ('pharmacy_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchNo', models.CharField(max_length=50, verbose_name='Batch Number')),
                ('noOfTabletsInStore', models.PositiveSmallIntegerField(default=0, verbose_name='Total Tablets in Store')),
                ('lastUpdated', models.DateTimeField(auto_now=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicine')),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicineprocuredetails')),
            ],
            options={
                'unique_together': {('medicine', 'batchNo')},
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billNo', models.CharField(max_length=50)),
                ('billDate', models.DateField(default=django.utils.timezone.now, verbose_name='Date Of Purchase')),
                ('noOfTabletsOrdered', models.PositiveSmallIntegerField(default=0)),
                ('totalPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('discount', models.PositiveSmallIntegerField(choices=[(0, 0), (5, 5), (10, 10)], default=0, verbose_name='Discount (%)')),
                ('discountedPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('transactionCompleted', models.CharField(default='N', max_length=1)),
                ('returnSales', models.CharField(default='N', max_length=2)),
                ('returnSalesNoOfTablets', models.PositiveSmallIntegerField(default=0)),
                ('returnSalesBillDate', models.DateField(default=django.utils.timezone.now, verbose_name='Date Of Return')),
                ('returnDiscountedPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('medStock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicinestock')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.patientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='PatientQueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_served', models.BooleanField(default=False)),
                ('served_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.patientdetail')),
            ],
            options={
                'ordering': ['is_served', 'queued_at'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noOfTabletsSold', models.PositiveIntegerField(verbose_name='Quantity Sold')),
                ('sale_amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Sale Amount')),
                ('sale_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Sale Date')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicine')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacyapp.medicinestock')),
            ],
        ),
    ]
